<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table value_Account number</name>
   <tag></tag>
   <elementGuidId>cce1d4da-74c2-4255-8e8f-b75bbea20231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div[2]/div[2]/div[7]/div/div[2]/div/div/table/tbody/tr/td[3]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pay-sundry-accounts-table__tbody-td-accountNumber</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9997200039</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;backoffice-container&quot;]/div[@class=&quot;backoffice-container__content&quot;]/div[2]/div[7]/div[@class=&quot;page pay-sundry-account-search&quot;]/div[@class=&quot;page__content pay-sundry-account-search__content&quot;]/div[@class=&quot;ldb-lib-search&quot;]/div[@class=&quot;ldb-lib-search__container_result&quot;]/table[@class=&quot;lib-table lib-table_scrollable&quot;]/tbody[@class=&quot;lib-table__tbody&quot;]/tr[@class=&quot;lib-table__tr lib-table__tr_clickable&quot;]/td[@class=&quot;lib-table__td pay-sundry-accounts-table__tbody-td pay-sundry-accounts-table__tbody-td_accountNumber lib-table__td_left&quot;]/div[@class=&quot;lib-table__td_content&quot;]/div[@class=&quot;pay-sundry-accounts-table__tbody-td-accountNumber&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='app']/div/div[3]/div[2]/div[2]/div[7]/div/div[2]/div/div/table/tbody/tr/td[3]/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account number'])[2]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBS_PRO'])[2]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account name'])[2]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//td[3]/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
