<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Currency</name>
   <tag></tag>
   <elementGuidId>3a9b974a-9b5a-45d4-a9b6-6e40921e34cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/div/div[2]/div/div/div[2]/div/div/form/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHFEURGBPUSD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[1]/div[@class=&quot;modal modal_pay-external-payment-modal modal_full&quot;]/div[@class=&quot;modal__dialog modal__dialog_full&quot;]/div[@class=&quot;modal__content modal__content_full&quot;]/div[@class=&quot;modal__body&quot;]/div[@class=&quot;ldb-lib-modal-box-container&quot;]/div[@class=&quot;ldb-lib-modal-box ldb-lib-modal-box_large&quot;]/form[@class=&quot;inputs_inline ldb-lib-form&quot;]/div[@class=&quot;lib-validation-scroll&quot;]/div[@class=&quot;lib-ldb-stepper&quot;]/div[@class=&quot;lib-ldb-stepper__content&quot;]/div[@class=&quot;ldb-lib-modal-box-container&quot;]/div[@class=&quot;ldb-lib-modal-box ldb-lib-modal-box_medium&quot;]/div[2]/div[@class=&quot;ldb-lib-money-model ldb-lib-money-model_input_l&quot;]/div[@class=&quot;inputs-number&quot;]/div[@class=&quot;input__group input__group_addon&quot;]/div[@class=&quot;select__group ldb-lib-money-model__currency-select&quot;]/select[@class=&quot;select__input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='modal']/div/div[2]/div/div/div[2]/div/div/form/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount and currency'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank account country'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Select)'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
