<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Label_City</name>
   <tag></tag>
   <elementGuidId>da418cd7-3dde-4193-afb2-18cc375e53b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/div/div[2]/div/div/div[2]/div/div/form/div/div[2]/div[2]/div/div[2]/div/div/div[3]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input__label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>2c79-82c3-893a-07da</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[1]/div[@class=&quot;modal modal_pay-external-payment-modal modal_full&quot;]/div[@class=&quot;modal__dialog modal__dialog_full&quot;]/div[@class=&quot;modal__content modal__content_full&quot;]/div[@class=&quot;modal__body&quot;]/div[@class=&quot;ldb-lib-modal-box-container&quot;]/div[@class=&quot;ldb-lib-modal-box ldb-lib-modal-box_large&quot;]/form[@class=&quot;inputs_inline ldb-lib-form&quot;]/div[@class=&quot;lib-validation-scroll&quot;]/div[@class=&quot;lib-ldb-stepper&quot;]/div[@class=&quot;lib-ldb-stepper__content&quot;]/div[@class=&quot;ldb-lib-modal-box-container&quot;]/div[@class=&quot;ldb-lib-modal-box ldb-lib-modal-box_large&quot;]/div[1]/div[1]/div[3]/div[@class=&quot;input__group&quot;]/div[@class=&quot;input__label-container&quot;]/label[@class=&quot;input__label&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='modal']/div/div[2]/div/div/div[2]/div/div/form/div/div[2]/div[2]/div/div[2]/div/div/div[3]/div/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address of beneficiary'])[1]/following::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiary name'])[1]/following::label[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post code'])[1]/preceding::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State / province'])[1]/preceding::label[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/div/div/label</value>
   </webElementXpaths>
</WebElementEntity>
