<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_Tasks</name>
   <tag></tag>
   <elementGuidId>d6b55811-6d84-4b67-a5c0-ffb815066593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;backoffice-container&quot;]/div[@class=&quot;navigation&quot;]/div[@class=&quot;backoffice-container__nav&quot;]/div[@class=&quot;backoffice-container__nav-content backoffice-container__nav-content_left&quot;]/div[@class=&quot;navigation-dropdown navigation-dropdown_left navigation-dropdown_hidden-xs&quot;]/ul[@class=&quot;navigation-dropdown__menu navigation-dropdown__menu_open&quot;]/li[@class=&quot;navigation-menu-item&quot;]/a[@class=&quot;navigation-menu-item__link&quot;][count(. | //*[@class = 'navigation-menu-item__link' and (text() = 'Tasks' or . = 'Tasks')]) = count(//*[@class = 'navigation-menu-item__link' and (text() = 'Tasks' or . = 'Tasks')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/div/div[3]/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navigation-menu-item__link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/operator/tasks</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tasks</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;backoffice-container&quot;]/div[@class=&quot;navigation&quot;]/div[@class=&quot;backoffice-container__nav&quot;]/div[@class=&quot;backoffice-container__nav-content backoffice-container__nav-content_left&quot;]/div[@class=&quot;navigation-dropdown navigation-dropdown_left navigation-dropdown_hidden-xs&quot;]/ul[@class=&quot;navigation-dropdown__menu navigation-dropdown__menu_open&quot;]/li[@class=&quot;navigation-menu-item&quot;]/a[@class=&quot;navigation-menu-item__link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='app']/div/div[3]/div/div/div/div[3]/ul/li[8]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Management'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[2]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposits'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>(//a[contains(@href, '/operator/tasks')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/ul/li[8]/a</value>
   </webElementXpaths>
</WebElementEntity>
